{{- include "redis-onprem.serviceAccount" (dict
  "root" .
  "create" .Values.serviceAccount.create
  "name" (include "langcache.serviceAccountName" .)
  "labelsTemplate" "langcache.labels"
  "annotations" .Values.serviceAccount.annotations
  "automount" .Values.serviceAccount.automount
) }}
