{{- include "redis-onprem.dataplane.hpa" (dict
  "root" .
  "enabled" .Values.server.autoscaling.enabled
  "name" (include "redis-agent-memory.fullname" .)
  "targetName" (include "redis-agent-memory.fullname" .)
  "component" "server"
  "labelsTemplate" "redis-agent-memory.labels"
  "minReplicas" .Values.server.autoscaling.minReplicas
  "maxReplicas" .Values.server.autoscaling.maxReplicas
  "targetCPUUtilizationPercentage" .Values.server.autoscaling.targetCPUUtilizationPercentage
  "targetMemoryUtilizationPercentage" .Values.server.autoscaling.targetMemoryUtilizationPercentage
) }}
