{{- if and (not .Values.controlplane.adminToken.existingSecret) .Values.controlplane.adminToken.autoGenerate }}
{{- $name := include "redis-playbook.controlplaneAdminTokenSecretName" . }}
{{- $key := .Values.controlplane.adminToken.secretKey }}
{{- $token := include "redis-onprem.lookupOrGenerateSecretToken" (dict "namespace" .Release.Namespace "name" $name "key" $key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "redis-playbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: controlplane
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ $key }}: {{ $token }}
{{- end }}
{{- if and (not .Values.controlplane.internalToken.existingSecret) .Values.controlplane.internalToken.autoGenerate }}
{{- $name := include "redis-playbook.controlplaneInternalTokenSecretName" . }}
{{- $key := .Values.controlplane.internalToken.secretKey }}
{{- $token := include "redis-onprem.lookupOrGenerateSecretToken" (dict "namespace" .Release.Namespace "name" $name "key" $key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "redis-playbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: controlplane
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ $key }}: {{ $token }}
{{- end }}
{{- if and (not .Values.identityService.controlToken.existingSecret) .Values.identityService.controlToken.autoGenerate }}
{{- $name := include "redis-playbook.identityServiceControlTokenSecretName" . }}
{{- $key := .Values.identityService.controlToken.secretKey }}
{{- $token := include "redis-onprem.lookupOrGenerateSecretToken" (dict "namespace" .Release.Namespace "name" $name "key" $key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "redis-playbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity-service
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ $key }}: {{ $token }}
{{- end }}
{{- if and (not .Values.identityService.runtimeToken.existingSecret) .Values.identityService.runtimeToken.autoGenerate }}
{{- $name := include "redis-playbook.identityServiceRuntimeTokenSecretName" . }}
{{- $key := .Values.identityService.runtimeToken.secretKey }}
{{- $token := include "redis-onprem.lookupOrGenerateSecretToken" (dict "namespace" .Release.Namespace "name" $name "key" $key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "redis-playbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity-service
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ $key }}: {{ $token }}
{{- end }}
