{{- include "redis-onprem.controlplane.service" (dict
  "root" .
  "name" (include "redis-agent-playbook.controlplaneName" .)
  "component" "controlplane"
  "labelsTemplate" "redis-agent-playbook.labels"
  "selectorLabelsTemplate" "redis-agent-playbook.selectorLabels"
  "type" .Values.controlplane.service.type
  "port" .Values.controlplane.service.port
) }}
---
{{ include "redis-onprem.dataplane.service" (dict
  "root" .
  "name" (include "redis-agent-playbook.dataplaneName" .)
  "component" "dataplane"
  "labelsTemplate" "redis-agent-playbook.labels"
  "selectorLabelsTemplate" "redis-agent-playbook.selectorLabels"
  "type" .Values.dataplane.service.type
  "port" .Values.dataplane.service.port
) }}
---
{{ include "redis-onprem.identityService.service" (dict
  "root" .
  "name" (include "redis-agent-playbook.identityServiceName" .)
  "component" "identity-service"
  "labelsTemplate" "redis-agent-playbook.labels"
  "selectorLabelsTemplate" "redis-agent-playbook.selectorLabels"
  "type" .Values.identityService.service.type
  "port" .Values.identityService.service.port
) }}
