{{- include "redis-onprem.serviceAccount" (dict
  "root" .
  "create" .Values.serviceAccount.create
  "name" (include "redis-agent-playbook.serviceAccountName" .)
  "labelsTemplate" "redis-agent-playbook.labels"
  "annotations" .Values.serviceAccount.annotations
  "automount" false
) }}
