apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseacls.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseACL
    listKind: RedisEnterpriseACLList
    plural: redisenterpriseacls
    singular: redisenterpriseacl
    shortNames:
      - reacl
  scope: Namespaced
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .spec.acl
          name: ACL
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          description: RedisEnterpriseACL represents an access control list definition
            for a Redis database.
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: RedisEnterpriseACLSpec defines the desired state of RedisEnterpriseACL
              properties:
                acl:
                  description: Redis ACL rule
                  type: string
              type: object
            status:
              description: RedisEnterpriseACLStatus defines the observed state of RedisEnterpriseACL
              properties:
                uid:
                  description: The internal UID of the Redis ACL object defined in the
                    Redis Enterprise Cluster.
                  type: string
                observedGeneration:
                  description: The most recent generation of this resource that was
                    observed and acted upon by the controller.
                  format: int64
                  type: integer
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
