apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisenterprisedatabaserolebindings.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseDatabaseRoleBinding
    listKind: RedisEnterpriseDatabaseRoleBindingList
    plural: redisenterprisedatabaserolebindings
    singular: redisenterprisedatabaserolebinding
    shortNames:
    - redbrolebinding
  scope: Namespaced
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - jsonPath: .spec.roleRef.name
      name: Role
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    schema:
      openAPIV3Schema:
        description: RedisEnterpriseDatabaseRoleBinding defines an association between
          users and roles within the Redis Enterprise cluster that grant access to
          databases.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RedisEnterpriseRoleBindingSpec defines the desired state
              of a RedisEnterpriseClusterRoleBinding or RedisEnterpriseDatabaseRoleBinding.
            properties:
              roleRef:
                description: RoleRef holds a reference to a role object. For a RedisEnterpriseClusterRoleBinding,
                  this can reference a RedisEnterpriseClusterRole object within the
                  same namespace by setting the 'kind' field to 'RedisEnterpriseClusterRole'
                  or leaving it empty; For a RedisEnterpriseDatabaseRoleBinding, this
                  can reference a RedisEnterpriseDatabaseRole object within the same
                  namespace by setting the 'kind' field to 'RedisEnterpriseDatabaseRole'
                  or leaving it empty; For both kinds of role bindings, this can also
                  reference an internal Role object within the Redis Enterprise Cluster,  in
                  which case the 'kind' field should be set to 'internal'. Note that
                  internal object references are only allowed when explicitly enabled
                  via the RedisEnterpriseCluster object.
                properties:
                  kind:
                    description: Kind of the referent.
                    type: string
                  name:
                    description: Name of the referent.
                    type: string
                  namespace:
                    description: Namespace of the referent.
                    type: string
                type: object
              subjects:
                description: Subjects holds references to the objects the role applies
                  to. By default, this is a reference to a RedisEnterpriseUser object
                  within the same namespace, in which case the 'kind' field can be
                  left empty, or set to RedisEnterpriseUser; Or, a reference to an
                  LDAP group, specified as a distinguished name, in which case the
                  'kind' field should be set to 'LDAPGroup'; Or, a reference to an
                  internal User object within the Redis Enterprise Cluster, in which
                  case the 'kind' field should be set to 'internal'; Note that internal
                  object references are only allowed when explicitly enabled via the
                  RedisEnterpriseCluster object.
                items:
                  description: A reference to another object.
                  properties:
                    kind:
                      description: Kind of the referent.
                      type: string
                    name:
                      description: Name of the referent.
                      type: string
                    namespace:
                      description: Namespace of the referent.
                      type: string
                  type: object
                type: array
            type: object
          status:
            description: RedisEnterpriseRoleBindingStatus defines the observed state
              of a RedisEnterpriseClusterRoleBinding or RedisEnterpriseDatabaseRoleBinding.
            properties:
              ldapMappings:
                description: LDAPMappings created for this role binding.
                items:
                  description: LDAPMapping describes an LDAPMapping object defined
                    within the Redis Enterprise Cluster.
                  properties:
                    uid:
                      description: The internal UID of the LDAPMapping object defined
                        in the Redis Enterprise Cluster.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: The most recent generation of this resource that was
                  observed and acted upon by the controller.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
