apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisenterpriseusers.app.redislabs.com
spec:
  group: app.redislabs.com
  names:
    kind: RedisEnterpriseUser
    listKind: RedisEnterpriseUserList
    plural: redisenterpriseusers
    singular: redisenterpriseuser
    shortNames:
    - reuser
  scope: Namespaced
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - jsonPath: .status.username
      name: Username
      type: string
    - jsonPath: .spec.email
      name: Email
      type: string
    - jsonPath: .status.signinStatus
      name: Signin Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    schema:
      openAPIV3Schema:
        description: RedisEnterpriseUser represents a user definition within a Redis
          Enterprise Cluster.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RedisEnterpriseUserSpec defines the desired state of a RedisEnterpriseUser.
            properties:
              alerts:
                description: Email alerts settings for this user. User alerts settings
                  are effective only when cluster alerts settings are configured.
                properties:
                  clusterAlerts:
                    description: UserClusterAlertSettings specifies cluster alerts
                      settings for a user.
                    properties:
                      enabled:
                        description: Determines whether cluster alerts are enabled
                          for the user.
                        type: boolean
                    required:
                    - enabled
                    type: object
                  databaseAlerts:
                    description: UserClusterAlertSettings specifies database alerts
                      settings for a user.
                    properties:
                      databases:
                        description: The databases for which alerts are enabled for
                          this user. If not specified, defaults to all databases.
                        items:
                          description: A reference to another object.
                          properties:
                            kind:
                              description: Kind of the referent.
                              type: string
                            name:
                              description: Name of the referent.
                              type: string
                            namespace:
                              description: Namespace of the referent.
                              type: string
                          type: object
                        type: array
                      enabled:
                        description: Determines whether database alerts are enabled
                          for the user.
                        type: boolean
                    required:
                    - enabled
                    type: object
                type: object
              email:
                description: The email address for the user.
                type: string
              passwordSecretName:
                description: Name of a secret holding the user's password. The secret
                  must reside in the same namespace as the RedisEnterpriseUser object,
                  and have a key named 'password' with the user's desired password.
                type: string
              username:
                description: The username associated with the user. The username must
                  be unique within the Redis Enterprise cluster, and include only
                  ASCII characters except &,<,>,". If not specified, a default username
                  is assigned and can be discovered via the status section of the
                  RedisEnterpriseUser.
                type: string
            required:
            - email
            - passwordSecretName
            type: object
          status:
            description: RedisEnterpriseUserStatus defines the observed state of a
              RedisEnterpriseUser.
            properties:
              observedGeneration:
                description: The most recent generation of this resource that was
                  observed and acted upon by the controller.
                format: int64
                type: integer
              passwordIssueDate:
                description: The date in which the password was set.
                type: string
              roles:
                description: List of roles assigned to the user.
                items:
                  description: A reference to another object.
                  properties:
                    kind:
                      description: Kind of the referent.
                      type: string
                    name:
                      description: Name of the referent.
                      type: string
                    namespace:
                      description: Namespace of the referent.
                      type: string
                  type: object
                type: array
              signinStatus:
                description: Sign-in status for the user.
                type: string
              uid:
                description: The internal UID of the User object defined in the Redis
                  Enterprise Cluster.
                type: string
              username:
                description: The effective username assigned for the user.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
