{{- if .Values.admission.limitToNamespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-enterprise-uninstaller
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-enterprise
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-enterprise-uninstaller
  labels:
    app: redis-enterprise
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-enterprise-uninstaller
  labels:
    app: redis-enterprise
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
subjects:
- kind: ServiceAccount
  name: redis-enterprise-uninstaller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: redis-enterprise-uninstaller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-enterprise-uninstaller
  labels:
    app: redis-enterprise
  annotations:
    {{- include "redis-enterprise-operator.annotations" . | nindent 4}}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: redis-enterprise
    spec:
      containers:
      - name: unlabel-namespace
        image: {{ include "redis-enterprise-operator.operator.image" . | printf "%s" | trim }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
        command:
        - install-helper
        args:
        - -action=unpatchNamespace
        - -namespace={{ .Release.Namespace }}
      serviceAccountName: redis-enterprise-uninstaller
      restartPolicy: OnFailure
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
{{- end }}{{- /* if limitToNamespace */ -}}
