apiVersion: v2
type: application

name: redis-agent-memory
description: Placeholder Helm chart for Redis Agent Memory

version: 0.0.1
appVersion: 0.0.1

home: https://redis.io
icon: https://redis.io/wp-content/uploads/2024/04/Logotype.svg
keywords:
  - redis
  - memory
maintainers:
  - name: Redis
    url: https://redis.io
