name: Release Redis Agent Memory Chart

on:
  workflow_dispatch:

jobs:
  call-release-workflow:
    uses: ./.github/workflows/release-chart-reusable.yaml
    with:
      chart_name: redis-agent-memory
      chart_path: ai/charts/redis-agent-memory
      tag_prefix: redis-agent-memory
    secrets: inherit
